#index:
#    path: /
#    controller: App\Controller\DefaultController::index
# config/routes.yaml
create:
   path: /event/create
   controller: App App\Controller\EventController::create
   methods: [POST]
logout:
    path: /logout
    # invalidate_session: true


